Ext.define('TestApp.store.Products', {
    extend: 'Ext.data.Store',
    alias: 'store.products',
    model: 'TestApp.model.Product',
    
    data: [
    {id: 1, name: 'Монитор', description: 'Игровой монитор 27"', price: 25000.99, quantity: 5},
    {id: 2, name: 'Клавиатура', description: 'Механическая клавиатура', price: 4500.50, quantity: 0},
    {id: 3, name: 'Мышь', description: 'Беспроводная мышь', price: 3200.00, quantity: 15},
    {id: 4, name: 'Наушники', description: 'Игровые наушники с микрофоном', price: 5600.00, quantity: 8},
    {id: 5, name: 'Коврик', description: 'Большой игровой коврик', price: 1200.00, quantity: 0},
    {id: 6, name: 'Видеокарта', description: 'Игровая видеокарта 8GB', price: 55400.00, quantity: 3},
    {id: 7, name: 'Процессор', description: '8-ядерный процессор', price: 28900.00, quantity: 7},
    {id: 8, name: 'Оперативная память', description: 'DDR4 16GB (2x8GB)', price: 6300.00, quantity: 12},
    {id: 9, name: 'Материнская плата', description: 'Gaming материнская плата', price: 15700.00, quantity: 4},
    {id: 10, name: 'SSD накопитель', description: 'NVMe SSD 1TB', price: 8900.00, quantity: 9},
    {id: 11, name: 'Блок питания', description: 'Мощный блок питания 750W', price: 7200.00, quantity: 6},
    {id: 12, name: 'Корпус', description: 'Игровой корпус с подсветкой', price: 5100.00, quantity: 10},
    {id: 13, name: 'Кулер для процессора', description: 'Башенный кулер', price: 3800.00, quantity: 8},
    {id: 14, name: 'Веб-камера', description: 'Full HD веб-камера', price: 4200.00, quantity: 0},
    {id: 15, name: 'Микрофон', description: 'Студийный USB микрофон', price: 6800.00, quantity: 5},
    {id: 16, name: 'Колонки', description: 'Стерео колонки 2.0', price: 3500.00, quantity: 7},
    {id: 17, name: 'Игровой руль', description: 'Руль с педалями для симуляторов', price: 21000.00, quantity: 2},
    {id: 18, name: 'Джойстик', description: 'Игровой джойстик для авиасимуляторов', price: 7400.00, quantity: 3},
    {id: 19, name: 'Геймпад', description: 'Беспроводной геймпад', price: 4900.00, quantity: 11},
    {id: 20, name: 'Сетевой фильтр', description: 'Пилот на 6 розеток', price: 1200.00, quantity: 20},
    {id: 21, name: 'ИБП', description: 'Источник бесперебойного питания', price: 13400.00, quantity: 4},
    {id: 22, name: 'USB концентратор', description: 'USB hub на 4 порта', price: 900.00, quantity: 0},
    {id: 23, name: 'Подставка для ноутбука', description: 'Охлаждающая подставка', price: 2200.00, quantity: 6},
    {id: 24, name: 'Сетевой кабель', description: 'Ethernet кабель 5м', price: 450.00, quantity: 50},
    {id: 25, name: 'HDMI кабель', description: 'HDMI 2.0 кабель 2м', price: 800.00, quantity: 30},
    {id: 26, name: 'Модульные кабели', description: 'Набор кабелей для БП', price: 3100.00, quantity: 3},
    {id: 27, name: 'Термопаста', description: 'Термоинтерфейс высокого качества', price: 500.00, quantity: 25},
    {id: 28, name: 'Набор отверток', description: 'Набор для сборки ПК', price: 1800.00, quantity: 8},
    {id: 29, name: 'Внешний HDD', description: 'Внешний жесткий диск 2TB', price: 5400.00, quantity: 7},
    {id: 30, name: 'Карта памяти', description: 'MicroSD карта 256GB', price: 1900.00, quantity: 15},
    {id: 31, name: 'USB флешка', description: 'USB 3.0 Flash Drive 64GB', price: 950.00, quantity: 22},
    {id: 32, name: 'Светильник', description: 'USB светильник для монитора', price: 1300.00, quantity: 0},
    {id: 33, name: 'Крепление для монитора', description: 'Кронштейн VESA', price: 3600.00, quantity: 4},
    {id: 34, name: 'Кресло игровое', description: 'Эргономичное игровое кресло', price: 28700.00, quantity: 2},
    {id: 35, name: 'Стол игровой', description: 'Стол с регулировкой высоты', price: 34200.00, quantity: 1},
    {id: 36, name: 'Коврик для мыши', description: 'Коврик с RGB подсветкой', price: 2400.00, quantity: 9},
    {id: 37, name: 'Чехол для наушников', description: 'Чехол для хранения', price: 700.00, quantity: 18},
    {id: 38, name: 'Чистящий набор', description: 'Для чистки клавиатуры и мыши', price: 600.00, quantity: 14},
    {id: 39, name: 'Стикеры', description: 'Набор декоративных стикеров', price: 300.00, quantity: 100},
    {id: 40, name: 'Подсветка', description: 'RGB лента для корпуса', price: 1500.00, quantity: 8},
    {id: 41, name: 'Вентилятор', description: 'Корпусной вентилятор 120mm', price: 850.00, quantity: 25},
    {id: 42, name: 'Реобас', description: 'Контроллер вентиляторов', price: 2100.00, quantity: 3},
    {id: 43, name: 'Внешняя звуковая карта', description: 'USB звуковая карта', price: 4300.00, quantity: 5},
    {id: 44, name: 'SPDIF кабель', description: 'Цифровой аудио кабель', price: 1100.00, quantity: 7},
    {id: 45, name: 'Портативный SSD', description: 'Внешний NVMe SSD 1TB', price: 12700.00, quantity: 4},
    {id: 46, name: 'Док-станция', description: 'Док-станция для ноутбука', price: 8900.00, quantity: 0},
    {id: 47, name: 'Переходник', description: 'DisplayPort to HDMI', price: 1200.00, quantity: 12},
    {id: 48, name: 'Кабель-удлинитель', description: 'USB удлинитель 3м', price: 650.00, quantity: 17},
    {id: 49, name: 'Аккумуляторы', description: 'Аккумуляторы АА (4 шт)', price: 1400.00, quantity: 0},
    {id: 50, name: 'Зарядное устройство', description: 'Зарядка для АКБ', price: 2200.00, quantity: 6},
    {id: 51, name: 'Очки синие', description: 'Очки для защиты от синего света', price: 1900.00, quantity: 9},
    {id: 52, name: 'Крепление для VR', description: 'Кронштейн для шлема VR', price: 3200.00, quantity: 2},
    {id: 53, name: 'Ламинатор', description: 'Карманный ламинатор', price: 2800.00, quantity: 1},
    {id: 54, name: 'Графический планшет', description: 'Планшет для рисования', price: 15600.00, quantity: 3},
    {id: 55, name: 'Беспроводной заряжатель', description: 'Зарядка Qi 15W', price: 2500.00, quantity: 0}
]
});